config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'
  resources :registrations
  resources :sessions
  resources :users, except: [:show] do
    member do
      put 'toggle_active', to: 'users#toggle_active'
    end
  end
  resources :students do
    put 'change_attendance', to: 'students#change_attendance'
    resources :likes, only: [:destroy]
    resources :comments, only: [:create] do
      resources :sub_comments, only: [:create]
      resources :likes, only: [:create]
    end
  end

  resources :homes, only: [:index]
  resources :posts, only: [:create] do
    resources :posts, only: [:create]
    resources :likes, only: %i[create destroy]
  end

  get 'logout' => 'sessions#destroy', :as => 'logout'
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :name, :lastname, :birthdate, :address, :school_grade, presence: true
  validates_format_of :name, :lastname, { with: /\A[a-zA-ZÀ-ÖØ-öø-ÿ\s]+\z/ }
  validate :cant_be_future
  validates :active_student, inclusion: { in: [true, false] }

  enum school_grade: { Inicial: 0, Primaria: 1, Secundaria: 2 }
  enum attendance: { presente: 0, ausente: 1, retirado: 2 }

  scope :count_attendance_type, ->(value) { where(attendance: value).count }

  def age
    age = (Date.today - birthdate) / 365.25
    age.to_int
  end

  def self.highlight_post_count
    Post.where(highlight_post: true).count
  end

  private

  def cant_be_future
    if birthdate.present? && !birthdate.future?
      true
    else
      errors.add(:birthdate, I18n.t('models.student.error_date'))
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :ensure_frame_response, only: %i[new edit]
  before_action :set_student, only: %i[show edit update destroy]
  before_action :require_login

  def index
    @presenter = StudentsPresenter.new(params)
    authorize Student
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    @student.user = current_user
    if @student.save
      redirect_to students_path
    else
      flash.now[:notice] = @student.errors
      render :new
    end
  end

  def show
    @comments = @student.comments.order(created_at: :desc)
    @comments_highlighted = @comments.where(highlight_comment: true).group_by do |c|
      c.created_at.to_date
    end
    @comments_not_highlighted = @comments.where(highlight_comment: false).group_by do |c|
      c.created_at.to_date
    end
  end

  def destroy
    authorize @student
    if @student.destroy
      redirect_to students_path, notice: t('.destroy_success')
    else
      redirect_to students_path, error: t('.destroy_error')
    end
  end

  def edit
    authorize @student
  end

  def update
    authorize @student
    if @student.update(student_params)
      redirect_to students_path
    else
      render :edit
    end
  end

  def change_attendance
    @student = Student.find(params[:student_id])
    @student.update(attendance: params[:attendance])
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :lastname, :address, :birthdate, :school_grade, :active_student, :attendance)
  end

  def ensure_frame_response
    return unless Rails.env.development?

    redirect_to users_list_path unless turbo_frame_request?
  end

  def not_authenticated
    redirect_to new_session_path, error: t('.not_authenticated')
  end
end

app/views/students/_attachments.html.erb
<% comment.files.each do |file| %>
  <div class='files-links'>
    <%= link_to file.filename , rails_blob_path(file, disposition: 'attachment') %>
  </div>
<% end %>

app/views/students/_comments.html.erb
<% highlight_styles = 'border-highlight' if is_highlighted %>
<% comments_by_day.each do |time, comments| %>
  <p class="comment-day"><%= (time == Date.today) ? t('date.today') : comments.first.decorate.format_date %></p>
  <% comments.each do |comment| %>
    <div class="comment-box <%= highlight_styles %>">
      <div class="comment-wrapper">
        <div class= "comment-name">
          <p><%= comment.user.full_name %></p>
          <span><%= comment.decorate.format_time %></span>
        </div>
        <div class= "like-box">
          <p><%= comment.likes.count %></p>
          <% pre_like = comment.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= button_to student_like_path(pre_like.id, student_id: student.id ),class:"btn-like btn-unlike", method: :delete do%>
              <%= image_tag "thumbs-up.svg", class:"like-image" %>        
            <%end%>
          <% else %>
            <%= button_to student_comment_likes_path(student, comment_id: comment), class:"btn-like", method: :post do%>
              <%= image_tag "thumbs-up.svg", class:"like-image" %>  
            <%end%>
          <%end%>
        </div>
      </div>
      <p class="comment-body"><%= comment.body %></p>
      <%= render 'attachments', comment: comment if comment.files.attached?%>
      <details open class= "comment-details-style">
        <summary></summary>
            <% comment.sub_comments.each do |sub_comment| %>
              <div class="comment-wrapper sub-comment-spacing">
                <div class="user-wrapper">
                  <p class="comment-name"><%= sub_comment.user.full_name %></p>
                  <span><%= sub_comment.decorate.format_time %></span>
                </div>
                <p class="comment-body"><%= sub_comment.body %></p>
              </div>
            <% end %>
        <div class='comment-details'>
          <%= form_with url: student_comment_sub_comments_path(student, comment_id: comment), method: :post do %>
            <div class='form-sub_comment'>
              <textarea name="body" rows="2" cols="50" placeholder='<%=t('comments.placeholder')%>' ></textarea>
              <%= button_tag :submit, class: 'form-btn-sub-comment' do %>
                <%= image_tag 'send.svg' %> 
              <% end %>
            </div>  
          <% end %>
        </div>
      </details>
    </div>
  <% end %>
<% end %>

app/views/students/_msg.html.erb
<% if errors.any? %>
  <div class="form-errors">
    <% errors.each do |err| %>
      <%= err %>
    <% end %>
  </div>
<% end %>

app/views/students/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal",
                      turbo_modal_target: "modal",
                      action: "turbo:submit-end->turbo-modal#submitEnd keyup@window->turbo-modal#closeWithKeyboard click@window->turbo-modal#closeBackground" },
                      class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
  <div class="container-modal">
    <div class="edit-h1">
      <%=tag.h1 t('student.edit')%>
    </div>
    <div class="form-modal">
      <%= form_with model: @student do |form|%>
        <div class="input-modal">
          <%= form.label t('student.name') %>
          <%= form.text_field :name, required: true %>
          <%= render 'msg', errors:@student.errors.messages_for(:name) %>
        </div>
        <div class="input-modal">
          <%= form.label t('student.surname') %>
          <%= form.text_field :lastname, required: true  %>
          <%= render 'msg', errors:@student.errors.messages_for(:lastname) %>
        </div>
        <div class="input-modal">
          <%= form.label t('student.address') %>
          <%= form.text_field :address, required: true  %>
        </div>
        <div class="input-modal">
          <%= form.label t('student.birthdate') %>
          <%= form.date_field :birthdate, required: true  %>
          <%= render 'msg', errors:@student.errors.messages_for(:birthdate) %>
        </div>
        <div class="input-modal">
          <%= form.label t('student.scholarship') %>
          <%= form.select :school_grade, Student.school_grades.keys, include_blank: false, required: true %>
        </div>
        <div class="radio-button-modal">
          <div class="active-question">
            <%= label_tag :active_student, t('student.active_student') %>
          </div>
          <div class="both-radio">
            <div class="radio-yes">
              <%= form.radio_button :active_student, true %>
              <%= label_tag t('student.yes') %>
            </div>
            <div class="radio-no">
              <%= form.radio_button :active_student, false %>
              <%= label_tag t('student.no') %>
            </div>
          </div>
        </div>
        <div class="button-modal">
          <%= form.submit t('student.edit_button'), class: "rounded-lg py-3 px-5 bg-red-600 text-white"%>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/students/index.html.erb
<div class="search-student">
  <div class="search-box">
    <%= form_with(model: @presenter.filter, url: students_path, method: :get) do |form| %>
      <div class="search-container">
        <%= form.text_field :query %>
      </div>
      <div>
        <%= button_tag :submit do %>
          <i class='search icon'></i>
        <% end %>
      </div>
    <% end %>
  </div>
    <%= link_to new_student_path, data: { turbo_frame: 'modal', controller: 'modal', action: 'click->modal#toggleBackground'  }, class:'user-create-button' do %>
      <%= image_tag 'add_user.svg' %>
      <span class="text-button"> <p><%= t('student.register_button') %></p></span>
  <% end %>
</div>
<div class="container-students">
  <div class="table-students">
    <table>
      <thead>
        <tr>
          <th><%= t('student.student') %></th>
          <th><%= t('student.age') %></th>
          <th><%= t('student.scholarship') %></th>
          <th><%= t('student.student_active') %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @presenter.students.each do |student| %>
          <tr>
            <td class= "student-user-name"><%= link_to student.full_name, student_path(student) %></td>
            <td><%= student.ages %></td>
            <td><%= student.school_grade %></td>
            <td><%= student.escolarizado %></td>
            <td class="edit-student-button">
              <% if policy(student).edit? %>
                <%= link_to edit_student_path(student), data: { turbo_frame: 'modal', controller: 'modal', action: 'click->modal#toggleBackground' } do %>
                  <%= image_tag "edit.svg" %>
                <% end %>
              <% end %>
            </td>
            <td>
            <div class='delete-student-container'>
              <div data-controller="modal">
                <span data-action= "click->modal#hideModal", class="delete-btn"> <%=image_tag 'trash-2.svg'%> </span>
                <div class='modal-delete hidden' data-modal-target="hideButton">
                  <p class='text-modal-delete'> <%= t('student.confirm_delete') %> </p>
                <%= button_to t('delete'), student_path(student), type: "button", class:"delete-btn-modal", method: :delete%>
                </div>
              </div>
            </div>  
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%== pagy_nav(@presenter.pagynate) %>
</div>

app/views/students/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal",
                      turbo_modal_target: "modal",
                      action: "turbo:submit-end->turbo-modal#submitEnd keyup@window->turbo-modal#closeWithKeyboard click@window->turbo-modal#closeBackground" },
                      class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
  <div class="container-modal">
    <div class="edit-h1">
      <%=tag.h1 t('student.create')%>
    </div>
    <div class="form-modal">
      <%= form_with model: @student do |form| %>
        <div class="input-modal">
          <%= form.label t('student.name') %>
          <%= form.text_field :name, required: true %>
          <%= render 'msg', errors:@student.errors.messages_for(:name) %>
        </div>
        <div class="input-modal">
          <%= form.label t('student.surname') %>
          <%= form.text_field :lastname, required: true  %>
          <%= render 'msg', errors:@student.errors.messages_for(:lastname) %>
        </div>
        <div class="input-modal">
          <%= form.label t('student.address') %>
          <%= form.text_field :address, required: true  %>
        </div>
        <div class="input-modal">
          <%= form.label t('student.birthdate') %>
          <%= form.date_field :birthdate, required: true  %>
          <%= render 'msg', errors:@student.errors.messages_for(:birthdate) %>
        </div>
        <div class="input-modal">
          <%= form.label t('student.scholarship') %>
          <%= form.select :school_grade, Student.school_grades.keys, include_blank: false, required: true %>
        </div>
        <div class="radio-button-modal">
          <div class="active-question">
            <%= label_tag :active_student, t('student.active_student') %>
          </div>
          <div class="both-radio">
            <div class="radio-yes">
              <%= form.radio_button :active_student, true %>
              <%= label_tag t('student.yes') %>
            </div>
            <div class="radio-no">
              <%= form.radio_button :active_student, false %>
              <%= label_tag t('student.no') %>
            </div>
          </div>
        </div>
        <div class="button-modal">
          <%= form.submit t('student.create_student'), class: "rounded-lg py-3 px-5 bg-red-600 text-white"%>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/students/show.html.erb
<div class='historial'>
  <%= link_to t('student.students') , students_path%>
  <p class='signito'> &ensp; > &ensp; </p>
  <p class='student-actual'><%=@student.decorate.full_name%></p>
</div>
<div class='container-detail'>
  <div class="student-data"> 
    <h2><%= @student.decorate.full_name%></h2>
    <h3><%= t('student.data_title') %></h3>
    <div class='student-info'>
      <p class='title-info'><%= t("student.birthdate")%></p>
      <p class='data-info'><%=  @student.birthdate%></p>
    </div>
    <div class='student-info'>
      <p class='title-info'><%=  t("student.address") %></p>
      <p class='data-info'><%=  @student.address%></p>
    </div>
    <div class='student-info'>
      <p class='title-info'><%= t("student.scholarship")%></p>
      <p class='data-info'><%=  @student.school_grade%></p>
    </div>
    <div class='student-info'>
      <p class='title-info'><%= t('student.student_active') %></p>
      <p class='data-info'><%=  @student.decorate.escolarizado%></p> 
    </div>
  </div>
  <div class='container-comment'>
    <div class='comment-details'>
      <p><%= t('comments.title') %></p>
      <%= form_with url: student_comments_path(@student), scope: :comment, method: :post, data: { controller: "emoji-picker"} do |f| %>
      <%= f.text_area :body, placeholder: t('comments.placeholder'),class: 'my-picker-comment', data: { emoji_picker_target: "input"} %>
        <div class='comment-button'>
          <div class='icons-button'> 
            <%= image_tag 'smile.svg', class: 'emojis-image', data: { action: "click->emoji-picker#toggle" , emoji_picker_target: "button"}%>
            <label class='files-attacher'>
              <%= image_tag 'add-files.svg' %>
              <div data-controller="file">
                <%= f.file_field :files, multiple: true, data: {action: 'change->file#addFile'}, active: 'image/jpg, image/png, application/pdf, application/msword' %>
                <ul class='files-list' data-file-target='list'> </ul>
              </div>
            </label>
            <%= f.check_box :highlight_comment %>
            <label><%= t('student.highlight_post')%></label>
          </div>
          <div> 
            <input type="submit", value= "Publicar", class= "post-button">
          </div>
        </div>  
      <% end %>
    </div>
    <div class="comments">
      <%= render partial: 'comments', locals: { comments_by_day: @comments_highlighted, student: @student, is_highlighted: true }%>
      <%= render partial: 'comments', locals: { comments_by_day: @comments_not_highlighted, student: @student, is_highlighted: false }%>
    </div>
  </div>
</div>