config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'
  resources :registrations
  resources :sessions
  resources :users, except: [:show] do
    member do
      put 'toggle_active', to: 'users#toggle_active'
    end
  end
  resources :students do
    put 'change_attendance', to: 'students#change_attendance'
    resources :likes, only: [:destroy]
    resources :comments, only: [:create] do
      resources :sub_comments, only: [:create]
      resources :likes, only: [:create]
    end
  end

  resources :homes, only: [:index]
  resources :posts, only: [:create] do
    resources :posts, only: [:create]
    resources :likes, only: %i[create destroy]
  end

  get 'logout' => 'sessions#destroy', :as => 'logout'
end

app/views/partials/_msg.html.erb
<% if flash[:error].present? || flash[:notice].present? %>
  <% flash.each do%>
    <div class="container-msg">
      <% if flash[:notice].present? %>
        <div class="notice-msg">
          <p id="notice"><%= flash[:notice] %></p>
        </div>
      <% end %>
      <% if flash[:error].present? %>
      <div class="error-msg">
        <p id="error"><%= flash[:error] %></p>
      </div>
      <% end %>
    </div>
  <% end %> 
<% end %>

app/views/partials/_navbar.html.erb
<div data-controller="modal"> 
  <div class="navbar">
    <div id="toggle-menu" >
      <%= image_tag 'menu.svg', data: {action: "click->modal#toggleMenu"}%>
    </div>
    <div class="nav-navigation">
      <%= link_to image_tag('home.svg'), homes_path, class: "#{'users-actual-page' if current_page?(homes_path)}"%>
      <%= link_to "Estudiantes", students_path, class: "#{'students-actual-page' if current_page?(students_path)}" %>
    </div>
    <div class="logged-user">
      <span data-action="click->modal#hideModal">
        <%= current_user.name %> <%= current_user.lastname %>
      </span>
      <div class="hidden" data-modal-target="hideButton">
        <%= link_to logout_path, class:'logout-btn' do %>
          <span class="text-button"> <p><%= t('session.logout_button') %></p></span>
          <%= image_tag 'log-out.svg' %>
        <% end %>
      </div>
    </div>
  </div>
  <div class= "burger-menu hidden" data-modal-target="burgerMenu">
    <h2>Hola <%= current_user.name%> (<%=current_user.role %>)</h2>
    <p>Mi perfil</p>
    <%= link_to "Roles", users_path%>
  </div>
</div> 