config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'
  resources :registrations
  resources :sessions
  resources :users, except: [:show] do
    member do
      put 'toggle_active', to: 'users#toggle_active'
    end
  end
  resources :students do
    put 'change_attendance', to: 'students#change_attendance'
    resources :likes, only: [:destroy]
    resources :comments, only: [:create] do
      resources :sub_comments, only: [:create]
      resources :likes, only: [:create]
    end
  end

  resources :homes, only: [:index]
  resources :posts, only: [:create] do
    resources :posts, only: [:create]
    resources :likes, only: %i[create destroy]
  end

  get 'logout' => 'sessions#destroy', :as => 'logout'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :students

  validates :name, :lastname, :email, presence: true
  validates_format_of :name, :lastname, { with: /\A[a-zA-ZÀ-ÖØ-öø-ÿ\s]+\z/ }
  validates :email, uniqueness: true
  validates_format_of :email, { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  enum role: { admin: 0, colaborador: 1 }

  def full_name
    name + ' ' + lastname
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy toggle_active]
  before_action :ensure_frame_response, only: %i[new edit]
  before_action :require_login

  # GET /users or /users.json
  def index
    @filter = UserFilter.new(User.all.order(created_at: :desc), filter_params)
    @pagy, @users = pagy(@filter.call)
  end

  # GET /users/new
  def new
    authorize current_user
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    authorize current_user
    @user = User.find(params[:id])
  end

  # POST /users or /users.json
  def create
    authorize current_user
    @user = User.create(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    authorize current_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def toggle_active
    authorize current_user
    @user.toggle(:is_active)
    @user.save
    redirect_to users_path
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    authorize current_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :lastname, :email, :password, :password_confirmation, :role)
  end

  def filter_params
    params.fetch(:user_filter, {}).permit(
      :query
    )
  end

  def ensure_frame_response
    return unless Rails.env.development?

    redirect_to root_path unless turbo_frame_request?
  end

  def not_authenticated
    redirect_to new_session_path, error: t('.not_authenticated')
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal",
                        turbo_modal_target: "modal",
                        action: "turbo:submit-end->turbo-modal#submitEnd keyup@window->turbo-modal#closeWithKeyboard click@window->turbo-modal#closeBackground" },
                        class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
  <div class="container-modal">
    <div class= "edit-h1"> 
      <h1 class="edit-h1"><%= t('user.modifUser') %></h1>
    </div>
    <div class= "form-modal"> 
      <%= form_with model: @user do |form| %>
        <div class="input-modal">
          <%= form.label t('user.name') %>
          <%= form.text_field :name %>
        </div>
        <div class="input-modal">
          <%= form.label t('user.surname') %>
          <%= form.text_field :lastname %>
        </div>
        <div class="input-modal">
          <%= form.label t('user.email') %>
          <%= form.text_field :email, disabled: true %>
        </div>
        <div class="input-modal">
          <%= form.label t('user.rol') %>
          <%= form.select :role, User.roles.keys, include_blank: false %>
        </div>
        <div class="button-modal">
          <%= form.submit t("user.save"), class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="search-student">
  <div class="search-box">
    <%= form_with(model: @filter, url: users_path, method: :get) do |form| %>
      <div class="search-container">
        <%= form.text_field :query %>
      </div>
      <div>
        <%= button_tag :submit do %>
          <i class='search icon'></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div>
    <% if policy(current_user).new?%>
      <%= link_to new_user_path, data: { turbo_frame: 'modal', controller: 'modal', action: 'click->modal#toggleBackground'  }, class:'user-create-button' do %>
        <%= image_tag 'add_user.svg' %>
        <span class="text-button"> 
          <p><%= t('user.register_button') %></p>
        </span>
      <% end %>
    <% end %>
  </div>
</div>
<div class="container-students">
  <div class="table-students">
    <table>
      <thead>
        <tr>
          <%=tag.th  t('user.name')%>
          <%=tag.th  t('user.surname')%>
          <%=tag.th  t('user.email')%>
          <% if policy(current_user).edit?%>
          <%=tag.th t('user.rol')%>
          <%=tag.th t('user.activate')%>
          <th></th>
          <% end %>
        </tr>
      </thead>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.lastname %></td>
          <td><%= user.email %></td>
          <% if policy(current_user).edit? %>
            <td> <%= user.role%>
            <td class="user-td-toggle" data-controller='toggle' data-toggle-url-value="<%=toggle_active_user_path(user.id)%>">
              <label class="switch">
                <input type="checkbox" data-action='click->toggle#userActivate' <% if user.is_active? %> checked <% end %> />
                <span class="slider round"></span>
              </label>
            </td>
            <td class="edit-student-button">
              <% if policy(user).edit? %>
                <%= link_to edit_user_path(user), data: { turbo_frame: 'modal', controller: 'modal', action: 'click->modal#toggleBackground' } do %>
                  <%= image_tag "edit.svg" %>
                <% end %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
  <%== pagy_nav(@pagy) %>
</div>
</body>

app/views/users/new.html.erb
<%= turbo_frame_tag "modal" do %>
 <%= tag.div data: { controller: "turbo-modal",
                      turbo_modal_target: "modal",
                      action: "turbo:submit-end->turbo-modal#submitEnd keyup@window->turbo-modal#closeWithKeyboard click@window->turbo-modal#closeBackground" },
                      class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
  <div class="container-modal">
    <div class= "edit-h1"> 
      <%=tag.h1 t('user.create'), class: "edit-h1"%>
    </div>
    <div class= "form-modal"> 
      <%= form_with model: @user do |form| %>
        <div class="input-modal">
          <%= form.label t('user.name') %>
          <%= form.text_field :name %>
        </div>
        <div class="input-modal">
          <%= form.label t('user.surname') %>
          <%= form.text_field :lastname %>
        </div>
        <div class="input-modal">
          <%= form.label t('user.email') %>
          <%= form.text_field :email %>
        </div>
        <div class="input-modal">
          <%= form.label t('user.rol') %>
          <%= form.select :role, User.roles.keys, include_blank: false%>
        </div>
        <div class="input-modal">
          <%= form.label t('user.pw') %>
          <%= form.password_field :password %>
        </div>
        <div class="input-modal">
          <%= form.label t('user.confirm_pw') %>
          <%= form.password_field :password_confirmation %>
        </div>
        <div class="button-modal">
          <%= form.submit t('user.create_user')%> 
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>