config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'
  resources :registrations
  resources :sessions
  resources :users, except: [:show] do
    member do
      put 'toggle_active', to: 'users#toggle_active'
    end
  end
  resources :students do
    put 'change_attendance', to: 'students#change_attendance'
    resources :likes, only: [:destroy]
    resources :comments, only: [:create] do
      resources :sub_comments, only: [:create]
      resources :likes, only: [:create]
    end
  end

  resources :homes, only: [:index]
  resources :posts, only: [:create] do
    resources :posts, only: [:create]
    resources :likes, only: %i[create destroy]
  end

  get 'logout' => 'sessions#destroy', :as => 'logout'
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def index
    @students = Student.all.order(created_at: :desc)

    @posts = Post.all.order(created_at: :desc)
    @posts_highlighted = @posts.where(highlight_post: true).group_by do |c|
      c.created_at.to_date
    end
    @posts_not_highlighted = @posts.where(highlight_post: false).group_by do |c|
      c.created_at.to_date
    end

    @date = I18n.l(Date.today, format: '%B %Y')
    @day = I18n.l(Date.today, format: '%A %d')
  end
end

app/views/homes/_attachments.html.erb
<% post.files.each do |file| %>
  <div class='files-links'>
    <%= link_to file.filename , rails_blob_path(file, disposition: 'attachment') %>
  </div>
<% end %>

app/views/homes/_attendance.html.erb
<div class="attendance-container">
  <h2> Asistencia </h2>
  <details open class= "comment-details-style">
    <summary></summary>
      <table>
        <thead>
          <th>Alumnado</th>   
          <th class="hover-text" data-hover="Alumnos presentes">P</th>   
          <th class="hover-text" data-hover="Alumnos ausentes">A</th>   
          <th class="hover-text" data-hover="Alumnos retirados">R</th>
        </thead>
        <tbody>
          <% students.each do |student| %>
            <tr>
              <td> <%= student.decorate.full_name %></td>
              <td class='present'
                data-controller="attendance" data-attendance-url-value="<%= student_change_attendance_path(student.id) %>" data-attendance-type-value='presente'>
                <input type='radio' name="attendance-<%= student.id %>" <%= "checked" if student.presente? %>  data-action='click->attendance#changeAttendance' id= <%= student.id %>> 
              </td>
              <td class='missing' 
                data-controller="attendance" data-attendance-url-value="<%= student_change_attendance_path(student.id)%>" data-attendance-type-value='ausente'>
                <input type='radio' name="attendance-<%= student.id %>" <%= "checked" if student.ausente? %> data-action='click->attendance#changeAttendance' id= <%= student.id %>> 
              </td>
              <td class='retired'
                data-controller="attendance" data-attendance-url-value="<%= student_change_attendance_path(student.id)%>" data-attendance-type-value='retirado'>
                <input type='radio' name="attendance-<%= student.id %>" <%= "checked" if student.retirado? %> data-action='click->attendance#changeAttendance' id= <%= student.id %>> 
               </td>
            </tr> 
          <%end%>
        </tbody>
      </table>
  </details>
</div>

app/views/homes/_posts.html.erb
<% highlight_styles = 'border-highlight' if is_highlighted %>
<% posts_by_day.each do |time, posts| %>
  <p class="comment-day"><%= (time == Date.today) ? t('date.today') : posts.first.decorate.format_date %></p>
  <% posts.each do |post| %>
    <div class="comment-box <%= highlight_styles %>">
      <div class="comment-wrapper">
        <div class= "comment-name">
          <p><%= post.user.full_name %></p>
          <span><%= post.decorate.format_time %></span>
        </div>
        <div class= "like-box">
          <p><%= post.likes.count %></p>
          <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
          <% if pre_like %>
            <%= button_to post_like_path(pre_like.id, post_id: post.id ),class:"btn-like btn-unlike", method: :delete do%>
              <%= image_tag "thumbs-up.svg", class:"like-image" %>
            <%end%>
          <% else %>
            <%= button_to post_likes_path(posts, post_id: post), class:"btn-like", method: :post do%>
              <%= image_tag "thumbs-up.svg", class:"like-image" %>
            <%end%>
          <%end%>
        </div>
      </div>
      <p class="comment-body"><%= post.body %></p>
      <%= render 'attachments', post: post if post.files.attached?%>
      <details open class= "comment-details-style">
        <summary></summary>
            <% post.children.each do |post_reply| %>
              <div class="comment-wrapper sub-comment-spacing">
                <div class="user-wrapper">
                  <p class="comment-name"><%= post_reply.user.full_name %></p>
                  <span><%= post_reply.decorate.format_time %></span>
                </div>
                <p class="comment-body"><%= post_reply.body %></p>
              </div>
            <% end %>
        <div class='comment-details'>
          <%= form_with url: post_posts_path(post), scope: :post, method: :post do %>
            <div class='form-sub_comment'>
              <textarea name="body" rows="2" cols="50" placeholder='<%=t('comments.placeholder')%>' ></textarea>
              <%= button_tag :submit, class: 'form-btn-sub-comment' do %>
                <%= image_tag 'send.svg' %> 
              <% end %>
            </div>
          <% end %>
        </div>
      </details>
    </div>
  <% end %>
<% end %>

app/views/homes/_summary_attendance.html.erb
<div class="attendance-detail-container">
  <details open class= "comment-details-style">
    <summary></summary>
      <table>
        <tbody>
          <tr>
            <td>Asistencia</td>
            <td><%= Student.count_attendance_type('presente') %></td>
            <td><%= Student.count_attendance_type('ausente') %></td>
            <td><%= Student.count_attendance_type('retirado') %></td>
          </tr>
          <tr>
            <td>Destacado</td>
            <td> <%= Student.highlight_post_count %> </td>
          </tr> 
          <tr>
            <td>Equipo</td>
            <td>
              <ul>
                <li>Pepito</li>
                <li>Maia</li>
                <li>Drako</li>
              </ul>
            </td>
          </tr>  
        </tbody>
      </table>
  </details>
</div>

app/views/homes/index.html.erb
<div class="home-container">
  <section class="post-section">
    <div class='home-date-container'>
      <div>
        <%= image_tag 'chevron-left.svg' %>
        <%= image_tag 'chevron-right.svg' %>
      </div>
      <div class="date">
        <div >
          <p><%= @date %></p>
          <p><%= @day %></p>
        </div>
        <%= image_tag 'arrow_drop_down.svg' %>
      </div>
    </div>
    <div class='container-comment post-index'>
      <div class='comment-details'>
        <p><%= t('home.index.title') %></p>
        <%= form_with url: posts_path, scope: :post, method: :post, data: { controller: "emoji-picker"} do |f| %>
        <%= f.text_area :body, placeholder: t('comments.placeholder'),class: 'my-picker-comment', data: { emoji_picker_target: "input"} %>
          <div class='comment-button'>
            <div class='icons-button'> 
              <%= image_tag 'smile.svg', class: 'emojis-image', data: { action: "click->emoji-picker#toggle" , emoji_picker_target: "button"}%>
              <label class='files-attacher'>
                <%= image_tag 'add-files.svg' %>
                <div data-controller="file">
                  <%= f.file_field :files, multiple: true, data: {action: 'change->file#addFile'}, active: 'image/jpg, image/png, application/pdf, application/msword' %>
                  <ul class='files-list' data-file-target='list'> </ul>
                </div>
              </label>
              <%= f.check_box :highlight_post %>
              <label><%= t('student.highlight_post')%></label>
            </div>
            <div> 
              <input type="submit", value= "Publicar", class= "post-button">
            </div>
          </div>  
        <% end %>
      </div>
      <div class="comments">
        <%= render partial: 'posts', locals: { posts_by_day: @posts_highlighted, is_highlighted: true } %>
        <%= render partial: 'posts', locals: { posts_by_day: @posts_not_highlighted, is_highlighted: false } %>
      </div>
    </div>
  </section>
  <section class="attendance-section">
    <%= render partial: 'attendance', locals: { students: @students } %>
    <%= render partial: 'summary_attendance'  %>
  </section>
</div>